theme: minima
title: My Website
description: My test website
author:
  name: Vít Petira
  email: aaa@aaaaaaaaaa.com
plugins:
  - jekyll-sitemap
  - jekyll-paginate
paginate: 2
paginate_path: "/pagestest/page:num/"
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/petira" }
    - { platform: twitter, user_url: "https://twitter.com/vitpetira" }
header_pages:
  - vypis/index.md
  - about/index.md
show_excerpts: true
